### ISSUE TITLE
to-do

### ISSUE THREAD

**Issue by Lanhild** [Lanhild/privs_switch#1]
- [ ] verify if the temporary priv countdown stays after a server crash
- [ ] verify the eligibility of the command with the `grant` and `switcher` privileges
- [ ] Verify and monitor how the mod affects performance of the machine (if it does)
